const mongoose = require('mongoose');

// Define the schema for logging prompt interactions
const PromptLogSchema = new mongoose.Schema({
  requestId: { type: String, required: true }, // Unique identifier for the request
  timestamp: { type: Date, default: Date.now }, // Timestamp of the log entry
  style: { type: String, default: "default" }, // Style or type of prompt

  inputs: {
    resume: { type: String, required: true }, // Resume input for the prompt
    jobDesc: { type: String, required: true }, // Job description input for the prompt
  },

  prompt: { type: String, required: true }, // The prompt sent to the model
  output: { type: String, required: true }, // The output generated by the model

  model: { type: String }, // Model used for generating the output
  usage: {
    prompt_tokens: Number, // Number of tokens in the prompt
    completion_tokens: Number, // Number of tokens in the completion
    total_tokens: Number, // Total number of tokens used
  },

  finishReason: { type: String } // Reason why the model finished
});

// Export the model
module.exports = mongoose.model('PromptLog', PromptLogSchema);
